/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryId = IDL.Nat;
export const TodoItemId = IDL.Nat;
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const TodoItem = IDL.Record({
  'id' : TodoItemId,
  'categoryId' : CategoryId,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
  'createTodoItem' : IDL.Func([IDL.Text, CategoryId], [TodoItemId], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteTodoItem' : IDL.Func([TodoItemId], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllTodoItems' : IDL.Func([], [IDL.Vec(TodoItem)], ['query']),
  'getTodosByCategory' : IDL.Func([CategoryId], [IDL.Vec(TodoItem)], ['query']),
  'toggleTodoCompleted' : IDL.Func([TodoItemId], [], []),
  'updateCategory' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [], []),
  'updateTodoItemText' : IDL.Func([TodoItemId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryId = IDL.Nat;
  const TodoItemId = IDL.Nat;
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const TodoItem = IDL.Record({
    'id' : TodoItemId,
    'categoryId' : CategoryId,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
    'createTodoItem' : IDL.Func([IDL.Text, CategoryId], [TodoItemId], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteTodoItem' : IDL.Func([TodoItemId], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllTodoItems' : IDL.Func([], [IDL.Vec(TodoItem)], ['query']),
    'getTodosByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(TodoItem)],
        ['query'],
      ),
    'toggleTodoCompleted' : IDL.Func([TodoItemId], [], []),
    'updateCategory' : IDL.Func([CategoryId, IDL.Text, IDL.Text], [], []),
    'updateTodoItemText' : IDL.Func([TodoItemId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };