/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : CategoryId,
  'name' : string,
  'color' : string,
}
export type CategoryId = bigint;
export interface TodoItem {
  'id' : TodoItemId,
  'categoryId' : CategoryId,
  'text' : string,
  'completed' : boolean,
  'timestamp' : bigint,
}
export type TodoItemId = bigint;
export interface _SERVICE {
  'createCategory' : ActorMethod<[string, string], CategoryId>,
  'createTodoItem' : ActorMethod<[string, CategoryId], TodoItemId>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteTodoItem' : ActorMethod<[TodoItemId], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllTodoItems' : ActorMethod<[], Array<TodoItem>>,
  'getTodosByCategory' : ActorMethod<[CategoryId], Array<TodoItem>>,
  'toggleTodoCompleted' : ActorMethod<[TodoItemId], undefined>,
  'updateCategory' : ActorMethod<[CategoryId, string, string], undefined>,
  'updateTodoItemText' : ActorMethod<[TodoItemId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];